/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated/renewals'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStatementsRouteImport } from './routes/_authenticated/statements'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedGrantsIndexRouteImport } from './routes/_authenticated/grants.index'
import { Route as AuthenticatedGrantsGrantIdRouteImport } from './routes/_authenticated/grants.$grantId'
import { Route as AuthenticatedHouseholdsIndexRouteImport } from './routes/_authenticated/households.index'
import { Route as AuthenticatedHouseholdsHouseholdIdRouteImport } from './routes/_authenticated/households.$householdId'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox.index'
import { Route as AuthenticatedInboxReviewRouteImport } from './routes/_authenticated/inbox.review'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeoplePersonIdRouteImport } from './routes/_authenticated/people.$personId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatementsRoute = AuthenticatedStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrantsIndexRoute =
  AuthenticatedGrantsIndexRouteImport.update({
    id: '/grants/',
    path: '/grants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGrantsGrantIdRoute =
  AuthenticatedGrantsGrantIdRouteImport.update({
    id: '/grants/$grantId',
    path: '/grants/$grantId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHouseholdsIndexRoute =
  AuthenticatedHouseholdsIndexRouteImport.update({
    id: '/households/',
    path: '/households/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHouseholdsHouseholdIdRoute =
  AuthenticatedHouseholdsHouseholdIdRouteImport.update({
    id: '/households/$householdId',
    path: '/households/$householdId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxReviewRoute =
  AuthenticatedInboxReviewRouteImport.update({
    id: '/inbox/review',
    path: '/inbox/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/people/',
    path: '/people/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeoplePersonIdRoute =
  AuthenticatedPeoplePersonIdRouteImport.update({
    id: '/people/$personId',
    path: '/people/$personId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/inbox/review': typeof AuthenticatedInboxReviewRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/grants/': typeof AuthenticatedGrantsIndexRoute
  '/households/': typeof AuthenticatedHouseholdsIndexRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/statements': typeof AuthenticatedStatementsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/inbox/review': typeof AuthenticatedInboxReviewRoute
  '/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/grants': typeof AuthenticatedGrantsIndexRoute
  '/households': typeof AuthenticatedHouseholdsIndexRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statements': typeof AuthenticatedStatementsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/_authenticated/households/$householdId': typeof AuthenticatedHouseholdsHouseholdIdRoute
  '/_authenticated/inbox/review': typeof AuthenticatedInboxReviewRoute
  '/_authenticated/people/$personId': typeof AuthenticatedPeoplePersonIdRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/grants/': typeof AuthenticatedGrantsIndexRoute
  '/_authenticated/households/': typeof AuthenticatedHouseholdsIndexRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/set-password'
    | '/dashboard'
    | '/donations'
    | '/renewals'
    | '/search'
    | '/settings'
    | '/statements'
    | '/tasks'
    | '/events/$eventId'
    | '/grants/$grantId'
    | '/households/$householdId'
    | '/inbox/review'
    | '/people/$personId'
    | '/events/'
    | '/grants/'
    | '/households/'
    | '/inbox/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/dashboard'
    | '/donations'
    | '/renewals'
    | '/search'
    | '/settings'
    | '/statements'
    | '/tasks'
    | '/events/$eventId'
    | '/grants/$grantId'
    | '/households/$householdId'
    | '/inbox/review'
    | '/people/$personId'
    | '/events'
    | '/grants'
    | '/households'
    | '/inbox'
    | '/people'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/set-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/donations'
    | '/_authenticated/renewals'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/statements'
    | '/_authenticated/tasks'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/grants/$grantId'
    | '/_authenticated/households/$householdId'
    | '/_authenticated/inbox/review'
    | '/_authenticated/people/$personId'
    | '/_authenticated/events/'
    | '/_authenticated/grants/'
    | '/_authenticated/households/'
    | '/_authenticated/inbox/'
    | '/_authenticated/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statements': {
      id: '/_authenticated/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AuthenticatedStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grants/': {
      id: '/_authenticated/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AuthenticatedGrantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grants/$grantId': {
      id: '/_authenticated/grants/$grantId'
      path: '/grants/$grantId'
      fullPath: '/grants/$grantId'
      preLoaderRoute: typeof AuthenticatedGrantsGrantIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/households/': {
      id: '/_authenticated/households/'
      path: '/households'
      fullPath: '/households/'
      preLoaderRoute: typeof AuthenticatedHouseholdsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/households/$householdId': {
      id: '/_authenticated/households/$householdId'
      path: '/households/$householdId'
      fullPath: '/households/$householdId'
      preLoaderRoute: typeof AuthenticatedHouseholdsHouseholdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/review': {
      id: '/_authenticated/inbox/review'
      path: '/inbox/review'
      fullPath: '/inbox/review'
      preLoaderRoute: typeof AuthenticatedInboxReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people/$personId': {
      id: '/_authenticated/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AuthenticatedPeoplePersonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatementsRoute: typeof AuthenticatedStatementsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedGrantsGrantIdRoute: typeof AuthenticatedGrantsGrantIdRoute
  AuthenticatedHouseholdsHouseholdIdRoute: typeof AuthenticatedHouseholdsHouseholdIdRoute
  AuthenticatedInboxReviewRoute: typeof AuthenticatedInboxReviewRoute
  AuthenticatedPeoplePersonIdRoute: typeof AuthenticatedPeoplePersonIdRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedGrantsIndexRoute: typeof AuthenticatedGrantsIndexRoute
  AuthenticatedHouseholdsIndexRoute: typeof AuthenticatedHouseholdsIndexRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatementsRoute: AuthenticatedStatementsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedGrantsGrantIdRoute: AuthenticatedGrantsGrantIdRoute,
  AuthenticatedHouseholdsHouseholdIdRoute:
    AuthenticatedHouseholdsHouseholdIdRoute,
  AuthenticatedInboxReviewRoute: AuthenticatedInboxReviewRoute,
  AuthenticatedPeoplePersonIdRoute: AuthenticatedPeoplePersonIdRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedGrantsIndexRoute: AuthenticatedGrantsIndexRoute,
  AuthenticatedHouseholdsIndexRoute: AuthenticatedHouseholdsIndexRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
